"""Affine Collapse Functor (ACF) Phi - public API."""

from .core import (
    ACFFunctor,
    ACFInvariant,
    ChebyshevReducer,
    EnrichedFunctor,
    FMAOperation,
    HornerReducer,
    KoopmanReducer,
    ACFFunctor,
    ACFInvariant,
    ReductionPath,
    ReductionResult,
    StratifiedReducer,
)
from .backends import acf_backend
from .composition import (
    CompositionCertificate,
    CompositionCertifier,
    DomainMapper,
    FunctorialComposer,
    LipschitzEstimator,
    PolynomialComposer,
)
from .koopman_adaptive import (
    AdaptiveKoopman,
    ObservableLibrary,
    SpectralDiagnostics,
    adaptive_koopman_reduce,
)
from .monad import FunctorMonad, MonadVerification
from .adjunction import CoFunctor, AdjunctionVerifier, AdjunctionVerification
from .lie_analysis import LieBracketAnalyzer, LieBracketResult, ParallelSchedule
from .cohomology import CohomologicalAnalysis, CohomologyAnalyzer, CohomologyGroup
from .constructible_sheaves import (
    ConstructibleSheaf,
    GluingDefect,
    OpenSet,
    SheafCohomologyResult,
    SheafSection,
)
from .moduli_spaces import GeodesicPath, ModuliAnalysis, ModuliPoint, ModuliSpace
from .persistent_homology import (
    PersistenceBar,
    PersistenceDiagram,
    PersistentHomologyEngine,
    SpectralPersistenceMap,
)
from .galois_symmetry import DetectedSymmetry, GaloisAnalyzer, GaloisGroup, SymmetryType
from .kolmogorov_entropy import ConservationTest, EntropyProfile, KolmogorovEntropy
from .superposition import CollapseResult, SuperpositionEngine, SuperpositionState
from .field_action import ActionComponents, FieldAction, FieldTheoryResult, PhaseTransition
from .act_topos import ACTTopos, ACFTopos, ToposAnalysis, ToposMorphism, ToposObject, TruthValue
from .self_modulation import (
    SelfModulatingFunctor,
    SheafReduction,
    TearType,
    TopologicalResidue,
    SheafInjector,
    ConvergenceMonad,
    AdaptiveReducer,
)
from .genesis import (
    GenesisOrchestrator,
    GenesisReport,
    ProgramGenerator,
    ProgramGenome,
    FingerprintEngine,
    TopologicalFingerprint,
    RelationDetector,
    MathematicalDiscovery,
    DiscoveryType,
    DiscoveryStrength,
)
from .genesis_auto_prover import (
    GenesisAutoProver,
    AutoProverReport,
    ProofAttempt,
    ProofStatus,
)
from .invariant_unified import (
    ACFInvariantUnified,
    AlphaCombinatorial,
    AlphaDefinition,
    AlphaEstimate,
    AlphaGeometric,
    AlphaSpectral,
    AlphaStochastic,
    AlphaODE,
    ACFInvariantUnified,
    AlphaUnificationTheorem,
    UnificationResult,
)

# New modules: maximizing ACF capabilities
from .koopman_delta_bounds import (
    KoopmanDeltaBounds,
    CompositionDelta,
    OptimalDimensionResult,
    SpectralBound,
    ConvergenceFamilyReport,
    delta_bounds_from_edmd,
    delta_bounds_from_svd,
)
from .mixed_composition import (
    MixedCompositionCertifier,
    PolynomialKoopmanCertifier,
    MixedCompositionCertificate,
    CompatibilityMatrix,
)
from .acf_inverse import (
    ACFInverse,
    PolynomialInverter,
    ChebyshevInverter,
    KoopmanInverter,
    InversionResult,
    InversionCertificate,
)
from .information_geometry import (
    InformationGeometry,
    FisherMetricACF,
    AffineMetricACF,
    LegendreDuality,
    DualityVerifier,
    InformationGeometryReport,
    polynomial_observables,
    fourier_observables,
)
from .thermodynamic_acf import (
    ThermodynamicACF,
    FreeEnergyComputer,
    CriticalityDetector,
    ThermodynamicReport,
    FreeEnergyProfile,
    PhaseTransition as ThermoPhaseTransition,
)
from .lie_analysis import NCComplexityAnalyzer, NCComplexityResult
from .auto_evolution import (
    FixedPointIterator,
    FixedPointResult,
    BifunctorialCycle,
    BifunctorialResult,
    ThermodynamicSearch,
    ThermodynamicSearchResult,
    ConfigurationPoint,
    AdaptiveRefinement,
    AdaptiveRefinementResult,
    RefinedInterval,
    ACFAutoEvolver,
    ACFAutoEvolverConfig,
    AutoEvolutionResult,
)
# Graph ACF
from .graph_acf import (
    GraphLaplacian,
    GraphReducer,
    GraphACFAnalyzer,
    GraphSignalEvolver,
    GraphSpectrum,
    GraphSignal,
    GraphReductionResult,
    GraphACFInvariants,
    GraphEvolutionResult,
    StandardGraphs,
)
# Neural ACF
from .neural_acf import (
    NeuralLayerReducer,
    NetworkACFAnalyzer,
    KoopmanNetworkDynamics,
    NeuralACFEvolver,
    LayerReductionResult,
    NetworkACFReport,
    LayerACFInvariants,
    KoopmanNetworkResult,
    NeuralEvolutionResult,
    build_test_mlp,
)
# Meta-Compiler
from .meta_compiler import (
    ACFMetaCompiler,
    MetaCompilerConfig,
    GrammarSpace,
    Grammar,
    GrammarPoint,
    BasisFamily,
    MetaCompilerTrace,
    MetaCompilerResult,
    GrammarEvaluator,
    GridSearch,
    RandomSearch,
    GreedySearch,
    BayesianSearch,
    AdaptiveGrammarSpace,
)
# Neural Architecture ACF
from .neural_arch_acf import (
    NeuralArchACF,
    ArchFingerprint,
    LayerFingerprint,
    LayerKind,
    ArchSimilarityResult,
    NASReplacementSearch,
    ArchitectureDatabase,
    build_known_architectures_db,
)
# Tensor ACF
from .tensor_acf import (
    TensorTrainCore,
    TensorTrainDecomposition,
    TensorACFInvariants,
    TensorReductionResult,
    TuckerDecomposition,
    TuckerReductionResult,
    ChebyshevTensorSampler,
    TensorTrainBuilder,
    TensorTrainEvaluator,
    TuckerBuilder,
    TuckerEvaluator,
    TensorACFReducer,
    TensorACFAnalyzer,
    StandardTensorFunctions,
)
# Matrix ACF
from .matrix_acf import (
    MatrixReductionResult,
    MatrixACFInvariants,
    MatrixFMAChain,
    ChebyshevMatrixReducer,
    MatrixExponential,
    MatrixSquareRoot,
    MatrixLogarithm,
    MatrixResolvent,
    MatrixSign,
    MatrixACFAnalyzer,
)

# ODE / Control ACF
from .ode_acf import (
    VectorFieldReducer,
    HJBReducer,
    LyapunovACF,
    TrajectoryACF,
    ODEACFInvariants,
    HJBInvariants,
    LyapunovCertificate,
    reduce_vector_field,
)
# Operator / Green Function ACF
from .operator_acf import (
    GreenFunctionReducer,
    IntegralOperatorACF,
    AttentionKernelReducer,
    KernelACFInvariants,
    AttentionKernelInvariants,
    reduce_green_function,
)
# Stochastic / PCE ACF (core + expansion)
from .stochastic_acf import (
    PolynomialChaosACF,
    StochasticReducer,
    PCECoefficients,
    StochasticACFInvariants,
    UncertaintyBound,
    compute_uncertainty_bound,
    # High-entropy extension
    HighEntropyAnalyzer,
    HighEntropyAnalysis,
    HurstResult,
    LevyStableResult,
    SpectralEntropyResult,
    # Financial risk
    FinancialACF,
    FinancialReport,
    VaRCertified,
    # Bayesian NN UQ
    BayesianNNAnalyzer,
    BayesianNNReport,
)
# Rational / Padé ACF
from .rational_acf import (
    PadeReducer,
    HardySpaceACF,
    PadeInvariants,
    HardySpaceInvariants,
    pade_reduce,
    hardy_reduce,
)

# Backward-compat alias (legacy API)
from .certified_koopman import (
    CertifiedKoopman,
    KoopmanBranch,
    KoopmanExactPolynomial,
    KoopmanResult,
    PolynomialDetector,
)

# Shared numerical infrastructure
from .shared_numerics import (
    AgentOrchestrator,
    ChebyshevBasis,
    LyapunovEstimator,
    LyapunovResult,
    SpectralClassification,
    SpectralClassifier,
    RenyiResult,
    compute_renyi_dimensions,
)

# ── Universal Constructor Engine ──────────────────────────────────────────
from .hypergraph_engine import (
    ComputableHyperGraph,
    HyperNode,
    HyperEdge,
    NodeKind,
    EdgeKind,
    SubGraph,
    build_linear_chain,
    build_residual_network,
    build_attention_block,
    build_stencil_grid,
    build_butterfly_fft,
    from_torch_module,
)
from .massive_algebra import (
    RandomizedSVD,
    SparseChebyshevOperator,
    CompressedLinearSolver,
    TensorTrainEngine,
    MassiveEigenSolver,
    OperatorCompressor,
    SpectralDecomposition,
    CompressedSolution,
    OperatorFunctionResult,
    TensorTrainDecomposition as MassiveTTDecomposition,
)
from .algorithm_forge import (
    AlgorithmForge,
    ProblemSpec,
    ProblemKind,
    StrategyKind,
    HardwareTarget,
    ForgedAlgorithm,
    StrategyCandidate,
    ProblemAnalyzer,
    StrategyExplorer,
    AlgorithmSynthesizer,
    AlgorithmVerifier,
    BackendSynthesizer,
    SynthesizedKernel,
    GraphPattern,
    BackendDecision,
    HardwareProfile,
    HardwareDetector,
    GraphPatternDetector,
    BackendSelector,
    BackendCodeGenerator,
)
from .universal_constructor import (
    UniversalConstructor,
    ConstructorMode,
    SystemKind,
    ConstructionStage,
    ConstructionPlan,
    ConstructedSystem,
    NeuralArchitect,
    PDESolverArchitect,
    GraphProcessorArchitect,
)

# ── Autonomous Discovery Engine ───────────────────────────────────────────
from .autonomous_discovery import (
    AutonomousDiscoveryEngine,
    DFTStructureDiscovery,
    OperatorStructureAnalyzer,
    ButterflyGraphSynthesizer,
    CoPoemRefinementLoop,
    KnowledgeGraph,
    DiscoveryResult,
    DiscoveryKind,
    KnowledgeEntry,
    # Level-5 Autonomy components
    TopologicalOperatorAnalyzer,
    TopologicalFingerprint,
    KoopmanStructuralAnalyzer,
    OperatorGrammarSearch,
    AutonomousRuleInduction,
    AutonomousRule,
    # Level-6: Algebraic Discovery Engine
    LinearOperatorAtomLibrary,
    OperatorAtom,
    AlgebraicDiscoveryEngine,
)

# CCD Engine — Motor para Alta Dimensionalidad
from .ccd_engine import (
    CCDEngine,
    CCDCertificate,
    RobustCCDCertificate,
    ChebyshevShell,  # DEPRECATED — use SpectralPreprocessor
    SpectralPreprocessor,
    SparseAdaptiveKernel,
    DiffusionGeometry,
    CoupledOscillators,
    ResonanceGroup,
    LocalEntropyOperator,
    LangevinPurifier,
    ManifoldDecoder,
    ScoreMatchingLangevin,
    preprocess_high_dim,
    estimate_intrinsic_dimension,
)

__version__ = "6.0.0"

__all__ = [
    "ACFFunctor",
    "ACFInvariant",
    "ACTTopos",
    "ACFInvariantUnified",
    "acf_backend",
    "ACFFunctor",
    "HornerReducer",
    "ChebyshevReducer",
    "KoopmanReducer",
    "StratifiedReducer",
    "ACFInvariant",
    "EnrichedFunctor",
    "FMAOperation",
    "ReductionResult",
    "ReductionPath",
    "FunctorialComposer",
    "CompositionCertifier",
    "CompositionCertificate",
    "PolynomialComposer",
    "LipschitzEstimator",
    "DomainMapper",
    "AdaptiveKoopman",
    "ObservableLibrary",
    "SpectralDiagnostics",
    "adaptive_koopman_reduce",
    "FunctorMonad",
    "MonadVerification",
    "CoFunctor",
    "AdjunctionVerifier",
    "AdjunctionVerification",
    "LieBracketAnalyzer",
    "LieBracketResult",
    "ParallelSchedule",
    "CohomologyAnalyzer",
    "CohomologicalAnalysis",
    "CohomologyGroup",
    "ConstructibleSheaf",
    "SheafSection",
    "SheafCohomologyResult",
    "OpenSet",
    "GluingDefect",
    "ModuliSpace",
    "ModuliAnalysis",
    "ModuliPoint",
    "GeodesicPath",
    "PersistentHomologyEngine",
    "SpectralPersistenceMap",
    "PersistenceDiagram",
    "PersistenceBar",
    "GaloisAnalyzer",
    "GaloisGroup",
    "DetectedSymmetry",
    "SymmetryType",
    "KolmogorovEntropy",
    "EntropyProfile",
    "ConservationTest",
    "SuperpositionEngine",
    "SuperpositionState",
    "CollapseResult",
    "FieldAction",
    "FieldTheoryResult",
    "ActionComponents",
    "PhaseTransition",
    "ACFTopos",
    "TruthValue",
    "ToposObject",
    "ToposMorphism",
    "ToposAnalysis",
    "acf_backend",
    "SelfModulatingFunctor",
    "SheafReduction",
    "TearType",
    "TopologicalResidue",
    "SheafInjector",
    "ConvergenceMonad",
    "AdaptiveReducer",
    "GenesisOrchestrator",
    "GenesisReport",
    "ProgramGenerator",
    "ProgramGenome",
    "FingerprintEngine",
    "TopologicalFingerprint",
    "RelationDetector",
    "MathematicalDiscovery",
    "DiscoveryType",
    "DiscoveryStrength",
    "GenesisAutoProver",
    "AutoProverReport",
    "ProofAttempt",
    "ProofStatus",
    "AlphaDefinition",
    "AlphaEstimate",
    "AlphaCombinatorial",
    "AlphaSpectral",
    "AlphaGeometric",
    "ACFInvariantUnified",
    "KoopmanBranch",
    "KoopmanResult",
    "PolynomialDetector",
    "KoopmanExactPolynomial",
    "CertifiedKoopman",
    "ChebyshevShell",  # DEPRECATED
    # Alpha unification
    "AlphaUnificationTheorem",
    "UnificationResult",
    # Koopman delta bounds
    "KoopmanDeltaBounds",
    "CompositionDelta",
    "OptimalDimensionResult",
    "SpectralBound",
    "ConvergenceFamilyReport",
    "delta_bounds_from_edmd",
    "delta_bounds_from_svd",
    # Mixed composition
    "MixedCompositionCertifier",
    "PolynomialKoopmanCertifier",
    "MixedCompositionCertificate",
    "CompatibilityMatrix",
    # ACF inverse
    "ACFInverse",
    "PolynomialInverter",
    "ChebyshevInverter",
    "KoopmanInverter",
    "InversionResult",
    "InversionCertificate",
    # Information geometry
    "InformationGeometry",
    "FisherMetricACF",
    "AffineMetricACF",
    "LegendreDuality",
    "DualityVerifier",
    "InformationGeometryReport",
    "polynomial_observables",
    "fourier_observables",
    # Thermodynamic ACF
    "ThermodynamicACF",
    "FreeEnergyComputer",
    "CriticalityDetector",
    "ThermodynamicReport",
    "FreeEnergyProfile",
    "ThermoPhaseTransition",
    # NC complexity
    "NCComplexityAnalyzer",
    "NCComplexityResult",
    # Auto-evolution engine
    "FixedPointIterator",
    "FixedPointResult",
    "BifunctorialCycle",
    "BifunctorialResult",
    "ThermodynamicSearch",
    "ThermodynamicSearchResult",
    "ConfigurationPoint",
    "AdaptiveRefinement",
    "AdaptiveRefinementResult",
    "RefinedInterval",
    "ACFAutoEvolver",
    "ACFAutoEvolverConfig",
    "AutoEvolutionResult",
    # Graph ACF
    "GraphLaplacian",
    "GraphReducer",
    "GraphACFAnalyzer",
    "GraphSignalEvolver",
    "GraphSpectrum",
    "GraphSignal",
    "GraphReductionResult",
    "GraphACFInvariants",
    "GraphEvolutionResult",
    "StandardGraphs",
    # Neural ACF
    "NeuralLayerReducer",
    "NetworkACFAnalyzer",
    "KoopmanNetworkDynamics",
    "NeuralACFEvolver",
    "LayerReductionResult",
    "NetworkACFReport",
    "LayerACFInvariants",
    "KoopmanNetworkResult",
    "NeuralEvolutionResult",
    "build_test_mlp",
    # Meta-Compiler
    "ACFMetaCompiler",
    "MetaCompilerConfig",
    "GrammarSpace",
    "Grammar",
    "GrammarPoint",
    "BasisFamily",
    "MetaCompilerTrace",
    "MetaCompilerResult",
    "GrammarEvaluator",
    "GridSearch",
    "RandomSearch",
    "GreedySearch",
    # Tensor ACF
    "TensorTrainCore",
    "TensorTrainDecomposition",
    "TensorACFInvariants",
    "TensorReductionResult",
    "TuckerDecomposition",
    "TuckerReductionResult",
    "ChebyshevTensorSampler",
    "TensorTrainBuilder",
    "TensorTrainEvaluator",
    "TuckerBuilder",
    "TuckerEvaluator",
    "TensorACFReducer",
    "TensorACFAnalyzer",
    "StandardTensorFunctions",
    # Matrix ACF
    "MatrixReductionResult",
    "MatrixACFInvariants",
    "MatrixFMAChain",
    "ChebyshevMatrixReducer",
    "MatrixExponential",
    "MatrixSquareRoot",
    "MatrixLogarithm",
    "MatrixResolvent",
    "MatrixSign",
    "MatrixACFAnalyzer",
    # ODE / Control ACF
    "VectorFieldReducer",
    "HJBReducer",
    "LyapunovACF",
    "TrajectoryACF",
    "ODEACFInvariants",
    "HJBInvariants",
    "LyapunovCertificate",
    "reduce_vector_field",
    # Operator / Green Function ACF
    "GreenFunctionReducer",
    "IntegralOperatorACF",
    "AttentionKernelReducer",
    "KernelACFInvariants",
    "AttentionKernelInvariants",
    "reduce_green_function",
    # Stochastic / PCE ACF
    "PolynomialChaosACF",
    "StochasticReducer",
    "PCECoefficients",
    "StochasticACFInvariants",
    "UncertaintyBound",
    "compute_uncertainty_bound",
    "HighEntropyAnalyzer",
    "HighEntropyAnalysis",
    "HurstResult",
    "LevyStableResult",
    "SpectralEntropyResult",
    "FinancialACF",
    "FinancialReport",
    "VaRCertified",
    "BayesianNNAnalyzer",
    "BayesianNNReport",
    # Rational / Padé ACF
    "PadeReducer",
    "HardySpaceACF",
    "PadeInvariants",
    "HardySpaceInvariants",
    "pade_reduce",
    "hardy_reduce",
    # Shared numerical infrastructure
    "AgentOrchestrator",
    "ChebyshevBasis",
    "LyapunovEstimator",
    "LyapunovResult",
    "SpectralClassification",
    "SpectralClassifier",
    "RenyiResult",
    "compute_renyi_dimensions",
    # ── Universal Constructor Engine ──
    # Hypergraph Engine
    "ComputableHyperGraph",
    "HyperNode",
    "HyperEdge",
    "NodeKind",
    "EdgeKind",
    "SubGraph",
    "build_linear_chain",
    "build_residual_network",
    "build_attention_block",
    "build_stencil_grid",
    "from_torch_module",
    # Massive Algebra
    "RandomizedSVD",
    "SparseChebyshevOperator",
    "CompressedLinearSolver",
    "TensorTrainEngine",
    "MassiveEigenSolver",
    "OperatorCompressor",
    "SpectralDecomposition",
    "CompressedSolution",
    "OperatorFunctionResult",
    "MassiveTTDecomposition",
    # Algorithm Forge
    "AlgorithmForge",
    "ProblemSpec",
    "ProblemKind",
    "StrategyKind",
    "HardwareTarget",
    "ForgedAlgorithm",
    "StrategyCandidate",
    "ProblemAnalyzer",
    "StrategyExplorer",
    "AlgorithmSynthesizer",
    "AlgorithmVerifier",
    # Universal Constructor
    "UniversalConstructor",
    "ConstructorMode",
    "SystemKind",
    "ConstructionStage",
    "ConstructionPlan",
    "ConstructedSystem",
    "NeuralArchitect",
    "PDESolverArchitect",
    "GraphProcessorArchitect",
    # Autonomous Discovery Engine
    "AutonomousDiscoveryEngine",
    "DFTStructureDiscovery",
    "OperatorStructureAnalyzer",
    "ButterflyGraphSynthesizer",
    "CoPoemRefinementLoop",
    "KnowledgeGraph",
    "DiscoveryResult",
    "DiscoveryKind",
    "KnowledgeEntry",
    # Level-5 Autonomy
    "TopologicalOperatorAnalyzer",
    "TopologicalFingerprint",
    "KoopmanStructuralAnalyzer",
    "OperatorGrammarSearch",
    "AutonomousRuleInduction",
    "AutonomousRule",
    # Level-6: Algebraic Discovery Engine
    "LinearOperatorAtomLibrary",
    "OperatorAtom",
    "AlgebraicDiscoveryEngine",
    # ── Stochastic Membrane (Level 0.5) ──────────────────────────────────────
    "SMConfig",
    "PurifiedTrajectory",
    "UncertaintyManifold",
    "SMOutput",
    "FilterAlgorithm",
    "NoiseFamily",
    "GaussianNoiseModel",
    "StudentTNoiseModel",
    "LevyStableNoiseModel",
    "AdaptiveNoiseModelSelector",
    "ParticleFilter",
    "UnscentedKalmanFilter",
    "TopologicalSeparator",
    "RegimeDetector",
    "MembraneMetaController",
    "StochasticMembrane",
    "EvolutionaryMembrane",
    # ── ACF Agents (Level 1-4) ─────────────────────────────────────────────
    "TAAAgent",
    "TAAState",
    "TAACertificate",
    "TAAMode",
    "DecayClass",
    "KoopmanSpectrum",
    "TAAAgentRealWorld",
    "ERGONAgent",
    "ERGONState",
    "ERGONCertificate",
    "LyapunovField",
    "PesinCertificate",
    "MixingIndex",
    "ERGONRealWorld",
    "GelfandTriple",
    "OTUResult",
    "RuelleSpectrum",
    "MultifractalSpectrum",
    "ThermodynamicPressure",
    "SpectralDampingProfile",
    "FrequencyMode",
    "OTURealWorld",
    "AutopoieticScientist",
    "PSALReport",
    "PSALPhase",
    "DiscoveredLaw",
    "KnowledgeBase",
    "LawStatus",
    # ── Calibration & Validation ───────────────────────────────────────────
    "ParameterCalibration",
    "CalibrationResult",
    "quick_calibrate",
    "NavierStokesValidator",
    "ValidationMetrics",
    "NavierStokes2DSpectral",
    "Lorenz96",
    "KuramotoSivashinsky",
    "FinancialGenerator",
    "validate_acf_on_real_systems",
    # ── Unified Pipeline ───────────────────────────────────────────────────
    "UnifiedPipeline",
    "PipelineResult",
    "StageResult",
    "StageStatus",
    "run_acf_pipeline",
    "demo_pipeline",
    # ── Distribution Theory for Hardware (Doctoral Proposal) ──────────────────
    "DualDistribution",
    "DirectionalSingularity",
    "SpectralTensor",
    "SingularityType",
    "DistributionOrder",
    "DistributionOperator",
    "CohomologicalGluingProtocol",
    "PatchDistribution",
    "GluingCondition",
    "CohomologicalGluingResult",
    "DistributionGelfandBridge",
    "DistributionTransferOperator",
    "DistributionGelfandState",
    "dirac",
    "heaviside",
    "dirac_derivative",
    "dirac_comb",
    "pv_cauchy",
    "distribution_to_gelfand_analysis",
    # ── Distribution Closures ──
    "OrderTruncationBound",
    "OrderTruncationAnalyzer",
    "ExactConvolutionResult",
    "AlgebraicConvolver",
    "CCDSingularityProjection",
    "CCDSingularityProjector",
    "AdaptiveCostBound",
    "AdaptiveCostAnalyzer",
    # ── Distribution Stability ──
    "StabilityAnalyzer",
    "StabilityCertificate",
    "PerturbationTrial",
    "PerturbationAnalysisResult",
    "analyze_stability",
    "PROOF_SKETCH_STABILITY",
]

# ── Stochastic Membrane (Level 0.5) ──────────────────────────────────────────
from .stochastic_membrane import (
    SMConfig,
    PurifiedTrajectory,
    UncertaintyManifold,
    SMOutput,
    FilterAlgorithm,
    NoiseFamily,
    GaussianNoiseModel,
    StudentTNoiseModel,
    LevyStableNoiseModel,
    AdaptiveNoiseModelSelector,
    ParticleFilter,
    UnscentedKalmanFilter,
    TopologicalSeparator,
    RegimeDetector,
    MembraneMetaController,
    StochasticMembrane,
    EvolutionaryMembrane,
)

# ── ACF Agents (Level 1-4) ──────────────────────────────────────────────────
from .taa_agent import (
    TAAAgent,
    TAAState,
    TAACertificate,
    TAAMode,
    DecayClass,
    KoopmanSpectrum,
    TAAAgentRealWorld,
)
from .ergon_agent import (
    ERGONAgent,
    ERGONState,
    ERGONCertificate,
    LyapunovField,
    PesinCertificate,
    MixingIndex,
    ERGONRealWorld,
)
from .gelfand_triple import (
    GelfandTriple,
    OTUResult,
    RuelleSpectrum,
    MultifractalSpectrum,
    ThermodynamicPressure,
    SpectralDampingProfile,
    FrequencyMode,
    OTURealWorld,
)
from .autopoietic_scientist import (
    AutopoieticScientist,
    PSALReport,
    PSALPhase,
    DiscoveredLaw,
    KnowledgeBase,
    LawStatus,
)

# ── Calibration & Validation ────────────────────────────────────────────────
from .parameter_calibration import (
    ParameterCalibration,
    CalibrationResult,
    quick_calibrate,
)
from .navier_stokes_validator import (
    NavierStokesValidator,
    ValidationMetrics,
    NavierStokes2DSpectral,
    Lorenz96,
    KuramotoSivashinsky,
    FinancialGenerator,
    validate_acf_on_real_systems,
)

# ── Unified Pipeline ────────────────────────────────────────────────────────
from .unified_pipeline import (
    UnifiedPipeline,
    PipelineResult,
    StageResult,
    StageStatus,
    run_acf_pipeline,
    demo_pipeline,
)

# ── Distribution Theory for Hardware (Doctoral Proposal) ──────────────────
from .distribution_theory import (
    DualDistribution,
    DirectionalSingularity,
    SpectralTensor,
    SingularityType,
    DistributionOrder,
    DistributionOperator,
    CohomologicalGluingProtocol,
    PatchDistribution,
    GluingCondition,
    CohomologicalGluingResult,
    dirac,
    heaviside,
    dirac_derivative,
    dirac_comb,
    pv_cauchy,
)

from .distribution_gelfand import (
    DistributionGelfandBridge,
    DistributionTransferOperator,
    DistributionGelfandState,
    distribution_to_gelfand_analysis,
)

# ── Distribution Closures (Four Open Problems Resolved) ──────────────────────
from .distribution_closures import (
    OrderTruncationBound,
    OrderTruncationAnalyzer,
    ExactConvolutionResult,
    AlgebraicConvolver,
    CCDSingularityProjection,
    CCDSingularityProjector,
    AdaptiveCostBound,
    AdaptiveCostAnalyzer,
)

# ── Distribution Stability (Doctoral Core — Perturbation Theory) ─────────────
from .distribution_stability import (
    StabilityAnalyzer,
    StabilityCertificate,
    PerturbationTrial,
    PerturbationAnalysisResult,
    analyze_stability,
    PROOF_SKETCH_STABILITY,
)
