"""Affine Collapse Functor (ACF) Phi - public API."""

from .core import (
    ACFFunctor,
    ACFInvariant,
    ChebyshevReducer,
    EnrichedFunctor,
    FMAOperation,
    HornerReducer,
    KoopmanReducer,
    ACFFunctor,
    ACFInvariant,
    ReductionPath,
    ReductionResult,
    StratifiedReducer,
)
from .backends import acf_backend
from .composition import (
    CompositionCertificate,
    CompositionCertifier,
    DomainMapper,
    FunctorialComposer,
    LipschitzEstimator,
    PolynomialComposer,
)
from .koopman_adaptive import (
    AdaptiveKoopman,
    ObservableLibrary,
    SpectralDiagnostics,
    adaptive_koopman_reduce,
)
from .monad import FunctorMonad, MonadVerification
from .adjunction import CoFunctor, AdjunctionVerifier, AdjunctionVerification
from .lie_analysis import LieBracketAnalyzer, LieBracketResult, ParallelSchedule
from .cohomology import CohomologicalAnalysis, CohomologyAnalyzer, CohomologyGroup
from .constructible_sheaves import (
    ConstructibleSheaf,
    GluingDefect,
    OpenSet,
    SheafCohomologyResult,
    SheafSection,
)
from .moduli_spaces import GeodesicPath, ModuliAnalysis, ModuliPoint, ModuliSpace
from .persistent_homology import (
    PersistenceBar,
    PersistenceDiagram,
    PersistentHomologyEngine,
    SpectralPersistenceMap,
)
from .galois_symmetry import DetectedSymmetry, GaloisAnalyzer, GaloisGroup, SymmetryType
from .kolmogorov_entropy import ConservationTest, EntropyProfile, KolmogorovEntropy
from .superposition import CollapseResult, SuperpositionEngine, SuperpositionState
from .field_action import ActionComponents, FieldAction, FieldTheoryResult, PhaseTransition
from .act_topos import ACTTopos, ACFTopos, ToposAnalysis, ToposMorphism, ToposObject, TruthValue
from .self_modulation import (
    SelfModulatingFunctor,
    SheafReduction,
    TearType,
    TopologicalResidue,
    SheafInjector,
    ConvergenceMonad,
    AdaptiveReducer,
)
from .genesis import (
    GenesisOrchestrator,
    GenesisReport,
    ProgramGenerator,
    ProgramGenome,
    FingerprintEngine,
    TopologicalFingerprint,
    RelationDetector,
    MathematicalDiscovery,
    DiscoveryType,
    DiscoveryStrength,
)
from .genesis_auto_prover import (
    GenesisAutoProver,
    AutoProverReport,
    ProofAttempt,
    ProofStatus,
)
from .invariant_unified import (
    ACFInvariantUnified,
    AlphaCombinatorial,
    AlphaDefinition,
    AlphaEstimate,
    AlphaGeometric,
    AlphaSpectral,
    AlphaStochastic,
    AlphaODE,
    ACFInvariantUnified,
    AlphaUnificationTheorem,
    UnificationResult,
)

# New modules: maximizing ACF capabilities
from .koopman_delta_bounds import (
    KoopmanDeltaBounds,
    CompositionDelta,
    OptimalDimensionResult,
    SpectralBound,
    ConvergenceFamilyReport,
    delta_bounds_from_edmd,
    delta_bounds_from_svd,
)
from .mixed_composition import (
    MixedCompositionCertifier,
    PolynomialKoopmanCertifier,
    MixedCompositionCertificate,
    CompatibilityMatrix,
)
from .acf_inverse import (
    ACFInverse,
    PolynomialInverter,
    ChebyshevInverter,
    KoopmanInverter,
    InversionResult,
    InversionCertificate,
)
from .information_geometry import (
    InformationGeometry,
    FisherMetricACF,
    AffineMetricACF,
    LegendreDuality,
    DualityVerifier,
    InformationGeometryReport,
    polynomial_observables,
    fourier_observables,
)
from .thermodynamic_acf import (
    ThermodynamicACF,
    FreeEnergyComputer,
    CriticalityDetector,
    ThermodynamicReport,
    FreeEnergyProfile,
    PhaseTransition as ThermoPhaseTransition,
)
from .lie_analysis import NCComplexityAnalyzer, NCComplexityResult
from .auto_evolution import (
    FixedPointIterator,
    FixedPointResult,
    BifunctorialCycle,
    BifunctorialResult,
    ThermodynamicSearch,
    ThermodynamicSearchResult,
    ConfigurationPoint,
    AdaptiveRefinement,
    AdaptiveRefinementResult,
    RefinedInterval,
    ACFAutoEvolver,
    ACFAutoEvolverConfig,
    AutoEvolutionResult,
)
# Graph ACF
from .graph_acf import (
    GraphLaplacian,
    GraphReducer,
    GraphACFAnalyzer,
    GraphSignalEvolver,
    GraphSpectrum,
    GraphSignal,
    GraphReductionResult,
    GraphACFInvariants,
    GraphEvolutionResult,
    StandardGraphs,
)
# Neural ACF
from .neural_acf import (
    NeuralLayerReducer,
    NetworkACFAnalyzer,
    KoopmanNetworkDynamics,
    NeuralACFEvolver,
    LayerReductionResult,
    NetworkACFReport,
    LayerACFInvariants,
    KoopmanNetworkResult,
    NeuralEvolutionResult,
    build_test_mlp,
)
# Meta-Compiler
from .meta_compiler import (
    ACFMetaCompiler,
    MetaCompilerConfig,
    GrammarSpace,
    Grammar,
    GrammarPoint,
    BasisFamily,
    MetaCompilerTrace,
    MetaCompilerResult,
    GrammarEvaluator,
    GridSearch,
    RandomSearch,
    GreedySearch,
    BayesianSearch,
    AdaptiveGrammarSpace,
)
# Neural Architecture ACF
from .neural_arch_acf import (
    NeuralArchACF,
    ArchFingerprint,
    LayerFingerprint,
    LayerKind,
    ArchSimilarityResult,
    NASReplacementSearch,
    ArchitectureDatabase,
    build_known_architectures_db,
)
# Tensor ACF
from .tensor_acf import (
    TensorTrainCore,
    TensorTrainDecomposition,
    TensorACFInvariants,
    TensorReductionResult,
    TuckerDecomposition,
    TuckerReductionResult,
    ChebyshevTensorSampler,
    TensorTrainBuilder,
    TensorTrainEvaluator,
    TuckerBuilder,
    TuckerEvaluator,
    TensorACFReducer,
    TensorACFAnalyzer,
    StandardTensorFunctions,
)
# Matrix ACF
from .matrix_acf import (
    MatrixReductionResult,
    MatrixACFInvariants,
    MatrixFMAChain,
    ChebyshevMatrixReducer,
    MatrixExponential,
    MatrixSquareRoot,
    MatrixLogarithm,
    MatrixResolvent,
    MatrixSign,
    MatrixACFAnalyzer,
)

# ODE / Control ACF
from .ode_acf import (
    VectorFieldReducer,
    HJBReducer,
    LyapunovACF,
    TrajectoryACF,
    ODEACFInvariants,
    HJBInvariants,
    LyapunovCertificate,
    reduce_vector_field,
)
# Operator / Green Function ACF
from .operator_acf import (
    GreenFunctionReducer,
    IntegralOperatorACF,
    AttentionKernelReducer,
    KernelACFInvariants,
    AttentionKernelInvariants,
    reduce_green_function,
)
# Stochastic / PCE ACF (core + expansion)
from .stochastic_acf import (
    PolynomialChaosACF,
    StochasticReducer,
    PCECoefficients,
    StochasticACFInvariants,
    UncertaintyBound,
    compute_uncertainty_bound,
    # High-entropy extension
    HighEntropyAnalyzer,
    HighEntropyAnalysis,
    HurstResult,
    LevyStableResult,
    SpectralEntropyResult,
    # Financial risk
    FinancialACF,
    FinancialReport,
    VaRCertified,
    # Bayesian NN UQ
    BayesianNNAnalyzer,
    BayesianNNReport,
)
# Rational / Padé ACF
from .rational_acf import (
    PadeReducer,
    HardySpaceACF,
    PadeInvariants,
    HardySpaceInvariants,
    pade_reduce,
    hardy_reduce,
)

# Backward-compat alias (legacy API)
from .certified_koopman import (
    CertifiedKoopman,
    KoopmanBranch,
    KoopmanExactPolynomial,
    KoopmanResult,
    PolynomialDetector,
)

# Shared numerical infrastructure
from .shared_numerics import (
    AgentOrchestrator,
    ChebyshevBasis,
    LyapunovEstimator,
    LyapunovResult,
    SpectralClassification,
    SpectralClassifier,
    RenyiResult,
    compute_renyi_dimensions,
)

__version__ = "5.0.0"

__all__ = [
    "ACFFunctor",
    "ACFInvariant",
    "ACTTopos",
    "ACFInvariantUnified",
    "acf_backend",
    "ACFFunctor",
    "HornerReducer",
    "ChebyshevReducer",
    "KoopmanReducer",
    "StratifiedReducer",
    "ACFInvariant",
    "EnrichedFunctor",
    "FMAOperation",
    "ReductionResult",
    "ReductionPath",
    "FunctorialComposer",
    "CompositionCertifier",
    "CompositionCertificate",
    "PolynomialComposer",
    "LipschitzEstimator",
    "DomainMapper",
    "AdaptiveKoopman",
    "ObservableLibrary",
    "SpectralDiagnostics",
    "adaptive_koopman_reduce",
    "FunctorMonad",
    "MonadVerification",
    "CoFunctor",
    "AdjunctionVerifier",
    "AdjunctionVerification",
    "LieBracketAnalyzer",
    "LieBracketResult",
    "ParallelSchedule",
    "CohomologyAnalyzer",
    "CohomologicalAnalysis",
    "CohomologyGroup",
    "ConstructibleSheaf",
    "SheafSection",
    "SheafCohomologyResult",
    "OpenSet",
    "GluingDefect",
    "ModuliSpace",
    "ModuliAnalysis",
    "ModuliPoint",
    "GeodesicPath",
    "PersistentHomologyEngine",
    "SpectralPersistenceMap",
    "PersistenceDiagram",
    "PersistenceBar",
    "GaloisAnalyzer",
    "GaloisGroup",
    "DetectedSymmetry",
    "SymmetryType",
    "KolmogorovEntropy",
    "EntropyProfile",
    "ConservationTest",
    "SuperpositionEngine",
    "SuperpositionState",
    "CollapseResult",
    "FieldAction",
    "FieldTheoryResult",
    "ActionComponents",
    "PhaseTransition",
    "ACFTopos",
    "TruthValue",
    "ToposObject",
    "ToposMorphism",
    "ToposAnalysis",
    "acf_backend",
    "SelfModulatingFunctor",
    "SheafReduction",
    "TearType",
    "TopologicalResidue",
    "SheafInjector",
    "ConvergenceMonad",
    "AdaptiveReducer",
    "GenesisOrchestrator",
    "GenesisReport",
    "ProgramGenerator",
    "ProgramGenome",
    "FingerprintEngine",
    "TopologicalFingerprint",
    "RelationDetector",
    "MathematicalDiscovery",
    "DiscoveryType",
    "DiscoveryStrength",
    "GenesisAutoProver",
    "AutoProverReport",
    "ProofAttempt",
    "ProofStatus",
    "AlphaDefinition",
    "AlphaEstimate",
    "AlphaCombinatorial",
    "AlphaSpectral",
    "AlphaGeometric",
    "ACFInvariantUnified",
    "KoopmanBranch",
    "KoopmanResult",
    "PolynomialDetector",
    "KoopmanExactPolynomial",
    "CertifiedKoopman",
    # Alpha unification
    "AlphaUnificationTheorem",
    "UnificationResult",
    # Koopman delta bounds
    "KoopmanDeltaBounds",
    "CompositionDelta",
    "OptimalDimensionResult",
    "SpectralBound",
    "ConvergenceFamilyReport",
    "delta_bounds_from_edmd",
    "delta_bounds_from_svd",
    # Mixed composition
    "MixedCompositionCertifier",
    "PolynomialKoopmanCertifier",
    "MixedCompositionCertificate",
    "CompatibilityMatrix",
    # ACF inverse
    "ACFInverse",
    "PolynomialInverter",
    "ChebyshevInverter",
    "KoopmanInverter",
    "InversionResult",
    "InversionCertificate",
    # Information geometry
    "InformationGeometry",
    "FisherMetricACF",
    "AffineMetricACF",
    "LegendreDuality",
    "DualityVerifier",
    "InformationGeometryReport",
    "polynomial_observables",
    "fourier_observables",
    # Thermodynamic ACF
    "ThermodynamicACF",
    "FreeEnergyComputer",
    "CriticalityDetector",
    "ThermodynamicReport",
    "FreeEnergyProfile",
    "ThermoPhaseTransition",
    # NC complexity
    "NCComplexityAnalyzer",
    "NCComplexityResult",
    # Auto-evolution engine
    "FixedPointIterator",
    "FixedPointResult",
    "BifunctorialCycle",
    "BifunctorialResult",
    "ThermodynamicSearch",
    "ThermodynamicSearchResult",
    "ConfigurationPoint",
    "AdaptiveRefinement",
    "AdaptiveRefinementResult",
    "RefinedInterval",
    "ACFAutoEvolver",
    "ACFAutoEvolverConfig",
    "AutoEvolutionResult",
    # Graph ACF
    "GraphLaplacian",
    "GraphReducer",
    "GraphACFAnalyzer",
    "GraphSignalEvolver",
    "GraphSpectrum",
    "GraphSignal",
    "GraphReductionResult",
    "GraphACFInvariants",
    "GraphEvolutionResult",
    "StandardGraphs",
    # Neural ACF
    "NeuralLayerReducer",
    "NetworkACFAnalyzer",
    "KoopmanNetworkDynamics",
    "NeuralACFEvolver",
    "LayerReductionResult",
    "NetworkACFReport",
    "LayerACFInvariants",
    "KoopmanNetworkResult",
    "NeuralEvolutionResult",
    "build_test_mlp",
    # Meta-Compiler
    "ACFMetaCompiler",
    "MetaCompilerConfig",
    "GrammarSpace",
    "Grammar",
    "GrammarPoint",
    "BasisFamily",
    "MetaCompilerTrace",
    "MetaCompilerResult",
    "GrammarEvaluator",
    "GridSearch",
    "RandomSearch",
    "GreedySearch",
    # Tensor ACF
    "TensorTrainCore",
    "TensorTrainDecomposition",
    "TensorACFInvariants",
    "TensorReductionResult",
    "TuckerDecomposition",
    "TuckerReductionResult",
    "ChebyshevTensorSampler",
    "TensorTrainBuilder",
    "TensorTrainEvaluator",
    "TuckerBuilder",
    "TuckerEvaluator",
    "TensorACFReducer",
    "TensorACFAnalyzer",
    "StandardTensorFunctions",
    # Matrix ACF
    "MatrixReductionResult",
    "MatrixACFInvariants",
    "MatrixFMAChain",
    "ChebyshevMatrixReducer",
    "MatrixExponential",
    "MatrixSquareRoot",
    "MatrixLogarithm",
    "MatrixResolvent",
    "MatrixSign",
    "MatrixACFAnalyzer",
    # ODE / Control ACF
    "VectorFieldReducer",
    "HJBReducer",
    "LyapunovACF",
    "TrajectoryACF",
    "ODEACFInvariants",
    "HJBInvariants",
    "LyapunovCertificate",
    "reduce_vector_field",
    # Operator / Green Function ACF
    "GreenFunctionReducer",
    "IntegralOperatorACF",
    "AttentionKernelReducer",
    "KernelACFInvariants",
    "AttentionKernelInvariants",
    "reduce_green_function",
    # Stochastic / PCE ACF
    "PolynomialChaosACF",
    "StochasticReducer",
    "PCECoefficients",
    "StochasticACFInvariants",
    "UncertaintyBound",
    "compute_uncertainty_bound",
    "HighEntropyAnalyzer",
    "HighEntropyAnalysis",
    "HurstResult",
    "LevyStableResult",
    "SpectralEntropyResult",
    "FinancialACF",
    "FinancialReport",
    "VaRCertified",
    "BayesianNNAnalyzer",
    "BayesianNNReport",
    # Rational / Padé ACF
    "PadeReducer",
    "HardySpaceACF",
    "PadeInvariants",
    "HardySpaceInvariants",
    "pade_reduce",
    "hardy_reduce",
    # Shared numerical infrastructure
    "AgentOrchestrator",
    "ChebyshevBasis",
    "LyapunovEstimator",
    "LyapunovResult",
    "SpectralClassification",
    "SpectralClassifier",
    "RenyiResult",
    "compute_renyi_dimensions",
]
