"""
Poema WASM Backend — WebAssembly Text Format (WAT) code generator.

Transpiles FMA chains to:
  - WAT (WebAssembly Text Format) — readable, inspectable source
  - WASM binary (if wat2wasm is available)
  - JavaScript ES module loader with optional Node.js + browser targets
  - Structured control flow matching the FMA evaluation loop

Architecture:
  WasmBackend(BackendProtocol)
    .compile(fma_seq, ast, domain, precision) -> BackendResult
    .emit_wat(fma_seq, precision, module_name) -> str
    .emit_js_loader(wasm_path, module_name) -> str
    .assemble(wat_source, out_path) -> Optional[str]  # calls wat2wasm if available
    .verify_available() -> bool

Precision mapping:
  fp64 → f64 (IEEE 754 double)
  fp32 → f32 (IEEE 754 single)
  complex128 → two f64 channels (real + imag)

WebAssembly FMA:
  WASM has no native FMA instruction in MVP. We emit:
    local.get $acc
    f64.mul  ;; or f32.mul
    local.get $bias
    f64.add  ;; or f32.add
  Modern engines (V8, SpiderMonkey) may fuse mul+add to HW FMA.
"""

from __future__ import annotations

import os
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, List, Optional, Tuple

from .protocol import BackendCapabilities, BackendProtocol, BackendResult

# ─────────────────────────────────────────────────────────────────────────────
# WAT code generation helpers
# ─────────────────────────────────────────────────────────────────────────────

_WAT_HEADER = """;; ================================================================
;; Poema FMA chain evaluator — WebAssembly Text Format (WAT)
;; Generated by poema.backends.wasm_backend
;; Module  : {module_name}
;; Depth   : {n_stages} FMA stages
;; Precision: {precision}
;; ================================================================
(module
"""

_WAT_CONST_SECTION = """;; --- Constant data: FMA weights and biases ---
;; Stored as f64 literals inlined into func body (constant folding by engine)
"""

_WAT_EVAL_FP64 = """;; poema_eval_fp64: (param f64 x) (result f64 y)
  (func (export "poema_eval_fp64") (param $x f64) (result f64)
    (local $acc f64)
    (local.set $acc (local.get $x))
{fma_body}
    (local.get $acc)
  )
"""

_WAT_EVAL_FP32 = """;; poema_eval_fp32: (param f32 x) (result f32 y)
  (func (export "poema_eval_fp32") (param $x f32) (result f32)
    (local $acc f32)
    (local.set $acc (local.get $x))
{fma_body}
    (local.get $acc)
  )
"""

_WAT_EVAL_COMPLEX = """;; poema_eval_complex: (param f64 xr xi) (result f64 yr yi)
;; Complex FMA: (wr+i*wi)*(ar+i*ai) + (br+i*bi)
  (func (export "poema_eval_complex") (param $xr f64) (param $xi f64)
        (result f64 f64)
    (local $ar f64)
    (local $ai f64)
    (local $tr f64)
    (local $ti f64)
    (local.set $ar (local.get $xr))
    (local.set $ai (local.get $xi))
{cmplx_body}
    (local.get $ar)
    (local.get $ai)
  )
"""

_WAT_BATCH_EVAL_FP64 = """;; poema_eval_batch_fp64: evaluate n elements from linear memory
;; Memory layout: input at offset 0, output at offset n*8
  (func (export "poema_eval_batch_fp64") (param $n i32)
    (local $i i32)
    (local $acc f64)
    (local.set $i (i32.const 0))
    (block $break
      (loop $loop
        (br_if $break (i32.ge_u (local.get $i) (local.get $n)))
        ;; load x[i] from memory at offset i*8
        (local.set $acc
          (f64.load (i32.mul (local.get $i) (i32.const 8))))
{batch_fma_body}
        ;; store y[i] at offset (n + i) * 8
        (f64.store
          (i32.mul (i32.add (local.get $n) (local.get $i)) (i32.const 8))
          (local.get $acc))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $loop)
      )
    )
  )
"""

_WAT_HORNER_FP64 = """;; poema_horner_fp64: Horner polynomial eval for degree (n_coeffs-1)
;; Memory: coefficients at offset 0 (f64 each), evaluate at x param
  (func (export "poema_horner_fp64")
        (param $x f64) (param $n_coeffs i32) (result f64)
    (local $acc f64)
    (local $k i32)
    (local.set $k (i32.sub (local.get $n_coeffs) (i32.const 1)))
    ;; acc = coeffs[n_coeffs - 1]
    (local.set $acc
      (f64.load (i32.mul (local.get $k) (i32.const 8))))
    (block $break
      (loop $loop
        (local.set $k (i32.sub (local.get $k) (i32.const 1)))
        (br_if $break (i32.lt_s (local.get $k) (i32.const 0)))
        ;; acc = acc * x + coeffs[k]
        (local.set $acc
          (f64.add
            (f64.mul (local.get $acc) (local.get $x))
            (f64.load (i32.mul (local.get $k) (i32.const 8)))))
        (br $loop)
      )
    )
    (local.get $acc)
  )
"""

_WAT_MEMORY = """;; Shared linear memory: 1 page = 64 KB (≥ 4096 f64 = 32 KB)
  (memory (export "memory") 2)
"""

_WAT_FOOTER = """)
;; end of module
"""

_JS_LOADER_TEMPLATE = """\
// Poema WASM Loader — auto-generated by poema.backends.wasm_backend
// Module: {module_name}  |  FMA depth: {n_stages}  |  Precision: {precision}
// Usage (Node.js / browser):
//   const {{ evalFMA, evalBatch }} = await loadPoema('{wasm_filename}');

export async function loadPoema(wasmPath = '{wasm_filename}') {{
  const source = typeof fetch !== 'undefined'
    ? await WebAssembly.instantiateStreaming(fetch(wasmPath))
    : WebAssembly.instantiate(require('fs').readFileSync(wasmPath));
  const {{ instance }} = await source;
  const exports = instance.exports;
  const mem = new Float64Array(exports.memory.buffer);

  /**
   * Evaluate the FMA chain on a single scalar.
   * @param {{number}} x — input value
   * @returns {{number}} evaluated FMA(x)
   */
  function evalFMA(x) {{
    return exports.poema_eval_fp64(x);
  }}

  /**
   * Evaluate the FMA chain on an array of n values.
   * Results written to the second half of WASM memory.
   * @param {{Float64Array}} xs — input array
   * @returns {{Float64Array}} evaluated outputs
   */
  function evalBatch(xs) {{
    const n = xs.length;
    mem.set(xs, 0);                    // copy input to WASM memory offset 0
    exports.poema_eval_batch_fp64(n);  // evaluate in-place
    return mem.slice(n, 2 * n);        // output is at offset n*8
  }}

  return {{ evalFMA, evalBatch, exports, memory: exports.memory }};
}}
"""


# ─────────────────────────────────────────────────────────────────────────────
# Backend class
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class WasmArtifact:
    """Result of WAT/WASM code generation."""
    module_name: str = ""
    wat_source: str = ""
    wasm_path: Optional[str] = None
    js_loader: str = ""
    n_stages: int = 0
    precision: str = "fp64"
    has_binary: bool = False

    def summary(self) -> str:
        binary_info = f"  WASM binary: {self.wasm_path}" if self.has_binary else \
                      "  WASM binary: not assembled (wat2wasm not found)"
        return (
            f"WasmArtifact [{self.module_name}]\n"
            f"  FMA depth  : {self.n_stages}\n"
            f"  Precision  : {self.precision}\n"
            f"  WAT lines  : {len(self.wat_source.splitlines())}\n"
            f"{binary_info}"
        )


class WasmBackend(BackendProtocol):
    """
    Poema WASM Backend.

    Transpiles FMA chains to WebAssembly Text Format (WAT) and optionally
    assembles them to WASM binary via wat2wasm.

    Produced artifacts:
      1. WAT source   — human-readable, inspectable WebAssembly text
      2. WASM binary  — assembled binary (if wat2wasm available)
      3. JS loader    — ES module with evalFMA() and evalBatch() API

    Performance note:
      V8/Node.js (TurboFan): typically 2–5× slower than native C.
      SpiderMonkey (Firefox): similar. WASM is JIT-compiled to native
      code, but lacks hardware-FMA intrinsics in standard MVP spec.

    Usage:
        backend = WasmBackend()
        result  = backend.compile(fma_seq, ast)
        print(result.emitted_code)    # WAT source
        # result.emitted_path         # .wat file path
        # result.extra["js_loader"]   # JS module loader string
        # result.extra["wasm_path"]   # .wasm path (if assembled)
    """

    _BUILD_DIR = Path(tempfile.gettempdir()) / "poema_wasm"

    def __init__(
        self,
        build_dir: Optional[str] = None,
        wat2wasm_bin: Optional[str] = None,
        emit_js_loader: bool = True,
    ):
        self._build_dir = Path(build_dir) if build_dir else self._BUILD_DIR
        self._build_dir.mkdir(parents=True, exist_ok=True)
        self._wat2wasm = wat2wasm_bin or self._find_wat2wasm()
        self._emit_js = emit_js_loader

    @staticmethod
    def _find_wat2wasm() -> Optional[str]:
        for name in ("wat2wasm", "wat2wasm-1.0", "wat2wasm-1"):
            try:
                subprocess.run([name, "--version"], capture_output=True, check=True)
                return name
            except (FileNotFoundError, subprocess.CalledProcessError):
                continue
        return None

    @property
    def capabilities(self) -> BackendCapabilities:
        return BackendCapabilities(
            name="wasm",
            supports_cpu=True,
            supports_gpu=False,
            supports_batched=True,
            supports_gradient=False,
            supports_cpp_emit=False,
            hardware_vendor="generic",
            max_fma_depth=100_000,
            precision_formats=["fp32", "fp64", "complex128"],
            notes=(
                "WebAssembly backend. Emits WAT + optional WASM binary. "
                "Runs everywhere: browsers, Node.js, edge compute. "
                f"wat2wasm: {'found' if self._wat2wasm else 'not found (WAT only)'}."
            ),
        )

    def verify_available(self) -> bool:
        return True   # WAT generation is always available (pure Python)

    # ── WAT code generation ──────────────────────────────────────────────────

    @staticmethod
    def _float_lit(v: Any, precision: str) -> str:
        """Format a numeric value as a WAT float literal."""
        f = float(v) if not isinstance(v, float) else v
        t = "f64" if precision in ("fp64", "double") else "f32"
        # WAT uses hex float for exact representation; use decimal for readability
        return f"({t}.const {f:.17g})"

    def _emit_fma_body(
        self,
        fma_sequence: List[Any],
        precision: str,
        indent: str = "    ",
        local_acc: str = "$acc",
    ) -> str:
        """Generate the inner WAT FMA body (sequence of mul + add ops)."""
        t = "f64" if precision in ("fp64", "double") else "f32"
        lines = []
        for instr in fma_sequence:
            w = float(getattr(instr.weight, "real", instr.weight))
            b = float(getattr(instr.bias, "real", instr.bias))
            lines += [
                f"{indent};; acc = {w:.6g} * acc + {b:.6g}",
                f"{indent}(local.set {local_acc}",
                f"{indent}  ({t}.add",
                f"{indent}    ({t}.mul",
                f"{indent}      ({t}.const {w:.17g})",
                f"{indent}      (local.get {local_acc}))",
                f"{indent}    ({t}.const {b:.17g})))",
            ]
        return "\n".join(lines)

    def _emit_complex_fma_body(
        self,
        fma_sequence: List[Any],
        indent: str = "    ",
    ) -> str:
        """WebAssembly complex FMA body (split real/imag)."""
        lines = []
        for instr in fma_sequence:
            wr = float(getattr(instr.weight, "real", instr.weight))
            wi = float(getattr(instr.weight, "imag", 0.0))
            br = float(getattr(instr.bias, "real", instr.bias))
            bi = float(getattr(instr.bias, "imag", 0.0))
            lines += [
                f"{indent};; complex FMA: ({wr:.4g}+{wi:.4g}i)*(ar+i*ai)+({br:.4g}+{bi:.4g}i)",
                f"{indent};; tr = wr*ar - wi*ai + br",
                f"{indent}(local.set $tr",
                f"{indent}  (f64.add (f64.sub",
                f"{indent}    (f64.mul (f64.const {wr:.17g}) (local.get $ar))",
                f"{indent}    (f64.mul (f64.const {wi:.17g}) (local.get $ai)))",
                f"{indent}    (f64.const {br:.17g})))",
                f"{indent};; ti = wr*ai + wi*ar + bi",
                f"{indent}(local.set $ti",
                f"{indent}  (f64.add (f64.add",
                f"{indent}    (f64.mul (f64.const {wr:.17g}) (local.get $ai))",
                f"{indent}    (f64.mul (f64.const {wi:.17g}) (local.get $ar)))",
                f"{indent}    (f64.const {bi:.17g})))",
                f"{indent}(local.set $ar (local.get $tr))",
                f"{indent}(local.set $ai (local.get $ti))",
            ]
        return "\n".join(lines)

    def emit_wat(
        self,
        fma_sequence: List[Any],
        precision: str = "fp64",
        module_name: str = "poema_fma",
        is_complex: bool = False,
    ) -> str:
        """Generate full WAT module source for the given FMA chain."""
        n = len(fma_sequence)
        src = _WAT_HEADER.format(
            module_name=module_name, n_stages=n, precision=precision)
        src += _WAT_MEMORY
        src += _WAT_CONST_SECTION

        if is_complex:
            body = self._emit_complex_fma_body(fma_sequence)
            src += _WAT_EVAL_COMPLEX.format(cmplx_body=body)
        else:
            body = self._emit_fma_body(fma_sequence, precision)
            batch_body = self._emit_fma_body(
                fma_sequence, precision, indent="        ", local_acc="$acc")
            if precision in ("fp64", "double"):
                src += _WAT_EVAL_FP64.format(fma_body=body)
                src += _WAT_BATCH_EVAL_FP64.format(batch_fma_body=batch_body)
                src += _WAT_HORNER_FP64
            else:
                src += _WAT_EVAL_FP32.format(fma_body=body)

        src += _WAT_FOOTER
        return src

    def emit_js_loader(
        self,
        wasm_filename: str,
        module_name: str = "poema_fma",
        n_stages: int = 0,
        precision: str = "fp64",
    ) -> str:
        """Generate a JavaScript ES module loader for the WASM artifact."""
        return _JS_LOADER_TEMPLATE.format(
            module_name=module_name,
            n_stages=n_stages,
            precision=precision,
            wasm_filename=wasm_filename,
        )

    def assemble(self, wat_source: str, out_path: str) -> Optional[str]:
        """
        Assemble WAT source to WASM binary using wat2wasm.
        Returns output path on success, None if wat2wasm unavailable.
        """
        if not self._wat2wasm:
            return None
        wat_path = out_path.replace(".wasm", ".wat")
        with open(wat_path, "w") as f:
            f.write(wat_source)
        try:
            r = subprocess.run(
                [self._wat2wasm, wat_path, "-o", out_path],
                capture_output=True, text=True)
            if r.returncode == 0 and os.path.exists(out_path):
                return out_path
        except Exception:
            pass
        return None

    # ── BackendProtocol interface ────────────────────────────────────────────

    def compile(
        self,
        fma_sequence: List[Any],
        source_ast: Any,
        domain: Tuple[float, float] = (-1.0, 1.0),
        precision: str = "fp64",
        module_name: Optional[str] = None,
        **kwargs,
    ) -> BackendResult:
        is_complex = kwargs.get("complex_mode", False)
        n = len(fma_sequence)
        mod_name = module_name or f"poema_fma_{precision}_{n}"

        wat_source = self.emit_wat(
            fma_sequence, precision, mod_name, is_complex=is_complex)

        # Write WAT to disk
        wat_path = str(self._build_dir / f"{mod_name}.wat")
        with open(wat_path, "w") as f:
            f.write(wat_source)

        # Attempt WASM assembly
        wasm_path = wat_path.replace(".wat", ".wasm")
        wasm_out = self.assemble(wat_source, wasm_path)

        # JS loader
        js_loader = ""
        if self._emit_js:
            wasm_fn = os.path.basename(wasm_out or wasm_path)
            js_loader = self.emit_js_loader(wasm_fn, mod_name, n, precision)
            js_path = wat_path.replace(".wat", ".mjs")
            with open(js_path, "w") as f:
                f.write(js_loader)

        # Python-side evaluation fallback (numpy-based for testing)
        ws = [float(getattr(i.weight, "real", i.weight)) for i in fma_sequence]
        bs = [float(getattr(i.bias, "real", i.bias)) for i in fma_sequence]

        def _eval_fallback(x):
            import numpy as np
            y = float(x) if not hasattr(x, "__len__") else __import__("numpy").asarray(x, dtype=float)
            for w, b in zip(ws, bs):
                y = w * y + b
            return y

        return BackendResult(
            callable_fn=_eval_fallback,
            emitted_code=wat_source,
            emitted_path=wat_path,
            fma_count=n,
            backend_name="wasm",
            extra={
                "wat_path"   : wat_path,
                "wasm_path"  : wasm_out,
                "js_loader"  : js_loader,
                "module_name": mod_name,
                "has_binary" : wasm_out is not None,
                "wat2wasm"   : self._wat2wasm,
            },
        )

    # ── Helpers ──────────────────────────────────────────────────────────────

    def inspect_artifact(self, result: BackendResult) -> str:
        """Return a summary of the emitted WAT/WASM artifact."""
        extra = result.extra
        lines = [
            "=" * 64,
            "  Poema WASM Backend — Artifact Inspection",
            "=" * 64,
            f"  FMA depth   : {result.fma_count}",
            f"  WAT path    : {extra.get('wat_path', '?')}",
            f"  WASM binary : {extra.get('wasm_path', 'not assembled')}",
            f"  Has binary  : {extra.get('has_binary', False)}",
            f"  wat2wasm    : {extra.get('wat2wasm', 'not found')}",
            f"  Module name : {extra.get('module_name', '?')}",
            "  " + "-" * 62,
        ]
        if result.emitted_code:
            preview = result.emitted_code.splitlines()[:40]
            lines += ["  WAT preview (40 lines):", "  " + "-" * 62]
            for ln in preview:
                lines.append("  " + ln)
        lines.append("=" * 64)
        return "\n".join(lines)

    def validate_wat(self, wat_source: str) -> bool:
        """
        Validate WAT syntax via wat2wasm --no-error-recovery.
        Returns True if valid, False otherwise.
        """
        if not self._wat2wasm:
            # Basic text validation only
            return "(module" in wat_source and ")" in wat_source
        with tempfile.NamedTemporaryFile(suffix=".wat", mode="w", delete=False) as f:
            f.write(wat_source)
            fname = f.name
        try:
            r = subprocess.run(
                [self._wat2wasm, fname, "--no-error-recovery", "-o", "/dev/null"],
                capture_output=True, text=True)
            return r.returncode == 0
        except Exception:
            return False
        finally:
            try:
                os.unlink(fname)
            except Exception:
                pass
